# Generated by Django 2.1.5 on 2019-03-19 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, help_text='Account first name', max_length=40, verbose_name='first_name')),
                ('middle_name', models.CharField(blank=True, help_text='Account middle name', max_length=40, verbose_name='middle_name')),
                ('last_name', models.CharField(blank=True, help_text='Account last name', max_length=40, verbose_name='middle_name')),
                ('is_verified', models.BooleanField(default=False, help_text='Indicates account has been verified for identity', verbose_name='is_verified')),
                ('is_admin', models.BooleanField(default=False, help_text='Indicates account has been admin for identity', verbose_name='is_admin')),
                ('kind', models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student')], default='student', help_text='Indicates account type student or teacher', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='profiles.Profile')),
            ],
        ),
    ]
