# Generated by Django 2.1.5 on 2019-03-20 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20190320_2019'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('name', 'type', 'primary_teacher')},
        ),
    ]
