# Generated by Django 2.1.5 on 2019-03-21 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20190321_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditory',
            fields=[
                ('name', models.CharField(help_text='auditory name', max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='auditory name')),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('name', models.CharField(help_text='building name', max_length=150, primary_key=True, serialize=False, unique=True, verbose_name='building name')),
                ('address', models.CharField(blank=True, help_text='building address', max_length=5000, verbose_name='building address')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('name', models.CharField(help_text='university name', max_length=150, unique=True, verbose_name='university name')),
                ('english_name', models.CharField(help_text='university english name', max_length=150, primary_key=True, serialize=False, unique=True, verbose_name='university english name')),
                ('description', models.CharField(blank=True, help_text='university description', max_length=5000, verbose_name='university description')),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.University'),
        ),
        migrations.AddField(
            model_name='auditory',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Building'),
        ),
    ]
